# RAGTrace Lite Configuration

llm:
  provider: "gemini"  # gemini | hcx
  api_key: "${GEMINI_API_KEY}"  # Environment variable
  model_name: "gemini-2.0-flash"  # Default model

embedding:
  provider: "default"  # default | bge_m3
  device: "auto"       # auto | cpu | cuda | mps (for BGE-M3)

data:
  input_path: "data/input"
  supported_formats: ["json", "xlsx"]

database:
  path: "db/ragtrace_lite.db"

results:
  output_path: "results"

evaluation:
  batch_size: 1         # RAGAS batch size - 1 for HCX rate limit
  show_progress: true   # Show progress bar during evaluation
  raise_exceptions: false  # Continue on errors