[project]
name = "ragtrace-lite"
version = "1.0.0"
description = "Lightweight RAG evaluation framework"

[project.dependencies]
ragas = ">=0.1.0"
pydantic = ">=2.0.0"
pydantic-settings = ">=2.0.0"
pandas = ">=2.0.0"
numpy = ">=1.24.0"
requests = ">=2.31.0"
pyyaml = ">=6.0"
datasets = ">=2.14.0"
python-dotenv = ">=1.0.0"
tqdm = ">=4.65.0"
tenacity = ">=8.0.0"
openpyxl = ">=3.1.0"

[project.optional-dependencies]
llm = [
    "google-generativeai>=0.3.0",
    "langchain>=0.0.300",
    "langchain-community>=0.0.10",
]
embeddings = [
    "sentence-transformers>=2.2.2",
    "torch>=2.0.0",
]
enhanced = [
    "plotly>=5.17.0",
    "psutil>=5.9.0",
    "scipy>=1.10.0",
    "scikit-learn>=1.2.0",
]
dev = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
    "black>=22.0.0",
    "ruff>=0.5.0",
    "mypy>=0.950",
    "isort>=5.10.0",
]

[tool.uv]
dev-dependencies = [
    "pytest>=7.0.0",
    "black>=22.0.0",
    "ruff>=0.5.0",
]
